server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: configServer
          uri: https://github.com/erik-antony-mg/microservicios.git
          search-paths: config-data
  application:
    name: config-service