server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
#          default-label: configServer
#          default-label: eureka
#          default-label: multiple-instances
#          default-label: gateway
          default-label: circuit-breaker
          uri: https://github.com/erik-antony-mg/microservicios.git
          search-paths: config-data

  application:
    name: config-service